# Generated by Django 4.1.2 on 2022-12-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie_app', '0020_date_is_active_film_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='movie_app.film')),
                ('number_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='movie_app.serie')),
                ('number_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three', to='movie_app.serie')),
                ('number_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='four', to='movie_app.serie')),
                ('number_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='five', to='movie_app.film')),
            ],
        ),
    ]
