# Generated by Django 4.1.2 on 2023-02-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0026_movie'),
        ('home_app', '0006_alter_slider_is_active_alter_slider_number_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='number_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='movie_app.film'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='number_2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='movie_app.serie'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='number_3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='three', to='movie_app.serie'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='number_4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='four', to='movie_app.serie'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='number_5',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='five', to='movie_app.film'),
        ),
    ]
