# Generated by Django 4.1.2 on 2023-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0026_movie'),
        ('home_app', '0007_alter_slider_number_1_alter_slider_number_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatelyUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('series', models.ManyToManyField(related_name='lately_updated', to='movie_app.serie')),
            ],
        ),
    ]
