# Generated by Django 4.1.2 on 2023-02-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0029_film_trailer_serie_trailer'),
        ('home_app', '0010_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('recent_films_slider_1', models.ManyToManyField(related_name='recent_films', to='movie_app.film')),
                ('recent_series_slider_2', models.ManyToManyField(related_name='recent_series', to='movie_app.serie')),
            ],
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
