# Generated by Django 4.1.2 on 2023-02-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_sitesetting_delete_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentlyUpdated',
        ),
    ]
