# Generated by Django 4.1.2 on 2023-02-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0029_film_trailer_serie_trailer'),
        ('home_app', '0012_delete_recentlyupdated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSetting',
            new_name='HomePageSlider',
        ),
    ]
