# Generated by Django 4.1.2 on 2023-02-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0014_sitesetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSetting',
        ),
    ]
