# Generated by Django 4.1.1 on 2022-10-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/films')),
                ('length', models.IntegerField()),
                ('imdb', models.FloatField(blank=True, null=True)),
                ('director', models.CharField(max_length=50)),
                ('banner', models.FileField(upload_to='uploads/banners')),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/series')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_count', models.IntegerField()),
                ('part_avg_length', models.IntegerField()),
                ('number', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.part')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.quality')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb', models.FloatField(blank=True, null=True)),
                ('director', models.CharField(max_length=50)),
                ('banner', models.FileField(upload_to='uploads/banners')),
                ('release_date', models.DateField()),
                ('genre', models.ManyToManyField(related_name='serie_genre', to='movie_app.genre')),
                ('seasons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.season')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.film')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb', models.FloatField(blank=True, null=True)),
                ('director', models.CharField(max_length=50)),
                ('banner', models.FileField(upload_to='uploads/banners')),
                ('release_date', models.DateField()),
                ('genre', models.ManyToManyField(related_name='movie_genre', to='movie_app.genre')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.type')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='film_genre', to='movie_app.genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.quality'),
        ),
    ]
