# Generated by Django 4.1.1 on 2022-10-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='film',
        ),
        migrations.RemoveField(
            model_name='type',
            name='serie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
