# Generated by Django 4.1.1 on 2022-10-30 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_remove_type_film_remove_type_serie_delete_movie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='seasons',
            new_name='season',
        ),
        migrations.RemoveField(
            model_name='season',
            name='part',
        ),
        migrations.AddField(
            model_name='part',
            name='number',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='season',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.season'),
            preserve_default=False,
        ),
    ]
