# Generated by Django 4.1.1 on 2022-10-30 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_rename_seasons_serie_season_remove_season_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='season',
        ),
        migrations.AddField(
            model_name='season',
            name='serie',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.serie'),
            preserve_default=False,
        ),
    ]
