# Generated by Django 4.1.1 on 2022-10-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_remove_serie_season_season_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='name',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
