# Generated by Django 4.1.1 on 2022-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_serie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='name',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
