# Generated by Django 4.1.1 on 2022-11-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_film_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='genre',
        ),
        migrations.AddField(
            model_name='serie',
            name='genre',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.genre'),
            preserve_default=False,
        ),
    ]
