# Generated by Django 4.1.1 on 2022-11-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_remove_serie_genre_serie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='quality',
        ),
        migrations.AddField(
            model_name='season',
            name='quality',
            field=models.ManyToManyField(related_name='serie_genre', to='movie_app.quality'),
        ),
    ]
