# Generated by Django 4.1.1 on 2022-11-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_remove_season_quality_season_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='quality',
        ),
        migrations.AddField(
            model_name='season',
            name='quality',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.quality'),
            preserve_default=False,
        ),
    ]
