# Generated by Django 4.1.1 on 2022-11-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_remove_season_quality_season_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='genre',
        ),
        migrations.AddField(
            model_name='serie',
            name='genre',
            field=models.ManyToManyField(related_name='serie_genre', to='movie_app.genre'),
        ),
    ]
