# Generated by Django 4.1.1 on 2022-11-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_remove_film_file_remove_film_quality_filmbyquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/backgrounds'),
        ),
        migrations.AlterField(
            model_name='film',
            name='banner',
            field=models.ImageField(upload_to='uploads/banners'),
        ),
    ]
