# Generated by Django 4.1.1 on 2022-11-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_serie_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
    ]
