# Generated by Django 4.1.2 on 2022-11-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0015_alter_film_cast_alter_serie_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.ManyToManyField(related_name='film_release_date', to='movie_app.releasedate'),
        ),
        migrations.AddField(
            model_name='serie',
            name='release_date',
            field=models.ManyToManyField(related_name='serie_release_date', to='movie_app.releasedate'),
        ),
    ]
