# Generated by Django 4.1.2 on 2022-11-30 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_rename_releasedate_date_serie_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='release_date',
        ),
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.date'),
            preserve_default=False,
        ),
    ]
