# Generated by Django 4.1.2 on 2022-11-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_remove_film_release_date_film_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='serie',
            name='end_date',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='movie_app.date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='release_date',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='release', to='movie_app.date'),
            preserve_default=False,
        ),
    ]
