# Generated by Django 4.1.2 on 2022-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0021_serievisit_filmvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
