# Generated by Django 4.1.2 on 2023-02-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0026_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='film',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='serie',
        ),
    ]
