# Generated by Django 4.1.2 on 2023-02-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_user_saved_movies_user_saved_series'),
        ('movie_app', '0027_remove_movie_film_remove_movie_serie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
