# Generated by Django 4.1.2 on 2023-02-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0027_remove_movie_film_remove_movie_serie'),
        ('user_app', '0002_user_saved_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='saved_movies',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_series',
            field=models.ManyToManyField(blank=True, related_name='saved_movies', to='movie_app.serie'),
        ),
    ]
