# Generated by Django 4.1.2 on 2023-02-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0028_delete_movie'),
        ('user_app', '0003_remove_user_saved_movies_user_saved_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_films',
            field=models.ManyToManyField(blank=True, related_name='saved_series', to='movie_app.film'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_series',
            field=models.ManyToManyField(blank=True, related_name='saved_series', to='movie_app.serie'),
        ),
    ]
